# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c358b011f99b31cdcab1960bd31744c8d2d995758234dfbf7d3b5e0e7f7d09f255d38f8ae1c1f6c6a9df8d58b52eed02a68ab3a2ae7cb919757500e28d3fdea

test:
  secret_key_base: f0de07450fcab9c3fe320eb2a664f12c730a3116a6cbce3da20c80c7d154461e2d91bbda387e41b07e08defa2752f2a5ad5f387502ddb2012b97cbd18a3518a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
